name: Build and Test Pull Request

# Trigger the workflow on push or pull request
on: [push, pull_request]

env:
  GOPROXY: https://proxy.golang.org/
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ github.job }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: test
        run: |
          make setup
          make deps
          make bindata
          make check
  test-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          # * Module download cache
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-${{ github.job }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: test
        run: |
          make setup
          make deps
          make bindata
          make check
